//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTable.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTable.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM Change WHERE Id={0}.
        /// </summary>
        public static string DeleteChange {
            get {
                return ResourceManager.GetString("DeleteChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM Schedule WHERE Id={0}.
        /// </summary>
        public static string DeleteSchedule {
            get {
                return ResourceManager.GetString("DeleteSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO Change(Date, LessonTimeId, StudyGroupId, LessonId, ClassroomId, TeacherId, AdditionalInfo) VALUES ( &apos;{0}&apos;, {1}, {2}, {3}, {4}, {5}, &apos;{6}&apos; ).
        /// </summary>
        public static string InsertChange {
            get {
                return ResourceManager.GetString("InsertChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO Classroom(Name) VALUES ( &apos;{0}&apos; ).
        /// </summary>
        public static string InsertClassroom {
            get {
                return ResourceManager.GetString("InsertClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO Lesson(Name) VALUES ( &apos;{0}&apos; ).
        /// </summary>
        public static string InsertLesson {
            get {
                return ResourceManager.GetString("InsertLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO LessonTime(Start, End) VALUES ( &apos;{0}&apos;, &apos;{1}&apos; ).
        /// </summary>
        public static string InsertLessonTime {
            get {
                return ResourceManager.GetString("InsertLessonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO Schedule(DayOfWeek, LessonTimeId, StudyGroupId, LessonId, ClassroomId, TeacherId, AdditionalInfo) VALUES ( {0}, {1}, {2}, {3}, {4}, {5}, &apos;{6}&apos; ).
        /// </summary>
        public static string InsertSchedule {
            get {
                return ResourceManager.GetString("InsertSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO StudyGroup(Name) VALUES ( &apos;{0}&apos; ).
        /// </summary>
        public static string InsertStudyGroup {
            get {
                return ResourceManager.GetString("InsertStudyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO Teacher(Name) VALUES ( &apos;{0}&apos; ).
        /// </summary>
        public static string InsertTeacher {
            get {
                return ResourceManager.GetString("InsertTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT Id, strftime(Date) as Date, LessonTimeId, StudyGroupId, LessonId, ClassroomId, TeacherId, AdditionalInfo FROM Change.
        /// </summary>
        public static string SelectChange {
            get {
                return ResourceManager.GetString("SelectChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM Classroom.
        /// </summary>
        public static string SelectClassroom {
            get {
                return ResourceManager.GetString("SelectClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM Lesson.
        /// </summary>
        public static string SelectLesson {
            get {
                return ResourceManager.GetString("SelectLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM LessonTime.
        /// </summary>
        public static string SelectLessonTime {
            get {
                return ResourceManager.GetString("SelectLessonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM Schedule.
        /// </summary>
        public static string SelectSchedule {
            get {
                return ResourceManager.GetString("SelectSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM StudyGroup.
        /// </summary>
        public static string SelectStudyGroup {
            get {
                return ResourceManager.GetString("SelectStudyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM Teacher.
        /// </summary>
        public static string SelectTeacher {
            get {
                return ResourceManager.GetString("SelectTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE Change SET Date=&apos;{0}&apos;, LessonTimeId={1}, StudyGroupId={2}, LessonId={3}, ClassroomId={4}, TeacherId={5}, AdditionalInfo=&apos;{6}&apos; WHERE Id={7}.
        /// </summary>
        public static string UpdateChange {
            get {
                return ResourceManager.GetString("UpdateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE Schedule SET DayOfWeek={0}, LessonTimeId={1}, StudyGroupId={2}, LessonId={3}, ClassroomId={4}, TeacherId={5}, AdditionalInfo=&apos;{6}&apos; WHERE Id={7}.
        /// </summary>
        public static string UpdateSchedule {
            get {
                return ResourceManager.GetString("UpdateSchedule", resourceCulture);
            }
        }
    }
}
